export { default as LoginPage } from "./Login"
export { default as VistaPizza } from "./VistaPizza"
export { default as HomeGerencia } from "./Home/HomeGerente"
export {default as FormsPizza} from "./FormsPizza"
export {default as GestionarPizza} from "./GestionPizza"